[build]
builder = "nixpacks"
buildCommand = "npm ci --force && npm run build"
nixpacks = { node-version = "21.7.3" }

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100